# Generated by Django 3.1.7 on 2021-03-21 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('create_id', models.CharField(default='system', max_length=30)),
                ('update_id', models.CharField(default='system', max_length=30)),
                ('anken_title', models.CharField(max_length=100)),
                ('anken_kianat', models.DateTimeField(default=datetime.datetime.now)),
                ('anken_syubetu', models.IntegerField(choices=[(1, '製品販売'), (2, 'SI'), (3, 'コンサル'), (4, 'その他')])),
                ('anken_naiyou', models.TextField()),
            ],
            options={
                'db_table': 'anken',
                'ordering': ['anken_kianat'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('create_id', models.CharField(default='system', max_length=30)),
                ('update_id', models.CharField(default='system', max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('customer_memo', models.TextField()),
                ('customer_web_site', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='Houmon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('create_id', models.CharField(default='system', max_length=30)),
                ('update_id', models.CharField(default='system', max_length=30)),
                ('houmon_at', models.DateTimeField(default=datetime.datetime.now)),
                ('houmon_mokuteki', models.IntegerField(choices=[(1, '製品説明'), (2, '案件'), (3, 'クレーム'), (4, '障害'), (5, 'その他')])),
                ('houmon_memo', models.TextField()),
                ('houmon_anken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelApp.anken')),
                ('houmon_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelApp.customer')),
            ],
            options={
                'db_table': 'houmon',
                'ordering': ['houmon_at'],
            },
        ),
        migrations.AddField(
            model_name='anken',
            name='anken_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelApp.customer'),
        ),
    ]
