# Generated by Django 3.1.7 on 2021-03-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0002_auto_20210322_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houmon',
            options={'ordering': ['houmon_titile']},
        ),
        migrations.AddField(
            model_name='houmon',
            name='houmon_titile',
            field=models.CharField(default='訪問目的は必須', max_length=100),
        ),
    ]
