# Generated by Django 3.1.7 on 2021-03-22 03:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0003_auto_20210322_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anken',
            name='anken_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelApp.customer', verbose_name='顧客名'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='anken_kianat',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='起案日'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='anken_naiyou',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='anken_syubetu',
            field=models.IntegerField(choices=[(1, '製品販売'), (2, 'SI'), (3, 'コンサル'), (4, 'その他')], verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='anken_title',
            field=models.CharField(max_length=100, verbose_name='案件名'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='create_id',
            field=models.CharField(default='system', max_length=30, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='update_id',
            field=models.CharField(default='system', max_length=30, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_id',
            field=models.CharField(default='system', max_length=30, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_memo',
            field=models.TextField(verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=30, verbose_name='顧客名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_web_site',
            field=models.URLField(blank=True, null=True, verbose_name='wwwサイト'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_id',
            field=models.CharField(default='system', max_length=30, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='create_id',
            field=models.CharField(default='system', max_length=30, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='houmon_anken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelApp.anken', verbose_name='案件'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='houmon_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='訪問日時'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='houmon_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelApp.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='houmon_memo',
            field=models.TextField(verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='houmon_mokuteki',
            field=models.IntegerField(choices=[(1, '製品説明'), (2, '案件'), (3, 'クレーム'), (4, '障害'), (5, 'その他')], verbose_name='目的種別'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='houmon_titile',
            field=models.CharField(default='訪問目的は必須', max_length=100, verbose_name='訪問タイトル'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='houmon',
            name='update_id',
            field=models.CharField(default='system', max_length=30, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default='1900-01-01', verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_id',
            field=models.CharField(default='system', max_length=30, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='社員姓'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='社員名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='memo',
            field=models.TextField(verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salary',
            field=models.FloatField(null=True, verbose_name='年商'),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_id',
            field=models.CharField(default='system', max_length=30, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='person',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='WWWサイト'),
        ),
    ]
